### ISSUE TITLE
今天2015.11.18  我使用Postman请求测试数据  一直提示 Header 'Date' required

### ISSUE THREAD

**Issue by homeboyStudio** [NXMIX/nextday-public-api#1]
headers参数正确

**Comment by jacobbubu** [comment]
你之前获得过 PartnerKey 和 Secret吗？如果有，你用 test.sh 或者 testMac.sh 测试一下有没有数据返回。

**Comment by homeboyStudio** [comment]
谢谢您，.sh测试通过有正确数据返回，应该是postman设置错误导致数据请求失败的，再次感谢。
